use_frameworks!

platform :ios, '10.0'

target 'JXLinearPageControl_Example' do
  pod 'JXLinearPageControl', :path => '../'

  target 'JXLinearPageControl_Tests' do
    inherit! :search_paths

    
  end
end
